from __future__ import annotations

import json
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from kompas_mcp.sketch_runtime import (  # noqa: E402
    DirectionAlias,
    FlatV60ThreadProfileSpec,
    Point,
    SketchModel,
    SketchReadbackExpectation,
    Vector2,
    build_flat_v60_thread_profile_preflight,
    build_preflight_state_card,
    build_readback_state_card,
    build_repair_hints,
    verify_sketch_preflight,
    verify_sketch_readback,
)


OUTPUT_DIR = ROOT / "sample" / "generated" / "sketch_runtime_algorithm_smoke_2026_05_20"


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _report_payload(label: str, report: Any, card: Any) -> dict[str, Any]:
    return {
        "label": label,
        "state_card": card.to_dict(),
        "repair_hints": [hint.to_dict() for hint in build_repair_hints(report.diagnostics)],
        "report": report.to_dict(),
    }


def _bad_direction_plan(plan: Any) -> Any:
    return type(plan)(
        **{
            **plan.__dict__,
            "direction_aliases": (
                DirectionAlias(
                    "radial_outward",
                    Vector2(0.0, -1.0),
                    "+y",
                    role="profile radial direction",
                ),
            ),
        }
    )


def _bad_readback_model(model: SketchModel) -> SketchModel:
    shifted_points: list[Point] = []
    for point in model.points:
        if point.id == "right_root":
            shifted_points.append(replace(point, y=point.y + 0.25))
        else:
            shifted_points.append(point)
    return SketchModel(
        name=f"{model.name}_bad_readback",
        expected_loops=model.expected_loops,
        points=tuple(shifted_points),
        primitives=model.primitives,
        metadata={**model.metadata, "fault": "right_root shifted by +0.25"},
    )


def main() -> None:
    spec = FlatV60ThreadProfileSpec(
        pitch=1.5,
        crest_y=10.0,
        root_y=8.7,
        outer_half_width=0.375,
        root_half_width=0.15,
    )
    plan = build_flat_v60_thread_profile_preflight(spec)

    preflight_ok = verify_sketch_preflight(plan, stage="physical_sample_preflight_ok")
    _write_json(
        OUTPUT_DIR / "01_preflight_ok.json",
        _report_payload("valid flat V60 profile preflight", preflight_ok, build_preflight_state_card(preflight_ok)),
    )

    preflight_bad_direction = verify_sketch_preflight(
        _bad_direction_plan(plan),
        stage="physical_sample_preflight_bad_direction",
    )
    _write_json(
        OUTPUT_DIR / "02_preflight_bad_direction.json",
        _report_payload(
            "inverted radial alias diagnostic",
            preflight_bad_direction,
            build_preflight_state_card(preflight_bad_direction),
        ),
    )

    expectation = SketchReadbackExpectation(plan.model)
    readback_ok = verify_sketch_readback(expectation, plan.model, stage="physical_sample_readback_ok")
    _write_json(
        OUTPUT_DIR / "03_readback_ok.json",
        _report_payload("matching readback snapshot", readback_ok, build_readback_state_card(readback_ok)),
    )

    readback_bad = verify_sketch_readback(
        expectation,
        _bad_readback_model(plan.model),
        stage="physical_sample_readback_bad_geometry",
    )
    _write_json(
        OUTPUT_DIR / "04_readback_bad_geometry.json",
        _report_payload(
            "shifted point readback diagnostic",
            readback_bad,
            build_readback_state_card(readback_bad),
        ),
    )

    summary = {
        "output_dir": str(OUTPUT_DIR),
        "files": [
            "01_preflight_ok.json",
            "02_preflight_bad_direction.json",
            "03_readback_ok.json",
            "04_readback_bad_geometry.json",
        ],
        "ok_cases": {
            "preflight_ok": preflight_ok.ok,
            "readback_ok": readback_ok.ok,
        },
        "expected_failures": {
            "preflight_bad_direction": [diagnostic.code for diagnostic in preflight_bad_direction.diagnostics],
            "readback_bad_geometry": [diagnostic.code for diagnostic in readback_bad.diagnostics],
        },
    }
    _write_json(OUTPUT_DIR / "summary.json", summary)
    (OUTPUT_DIR / "README.md").write_text(
        "# Sketch runtime algorithm smoke files\n\n"
        "Generated by `sample/create_sketch_runtime_algorithm_smoke_2026_05_20.py`.\n\n"
        "- `01_preflight_ok.json`: valid flat V60 profile through topology/frame/direction/"
        "constraints/relations/measurements/orientation/dimensions checks.\n"
        "- `02_preflight_bad_direction.json`: same profile with inverted radial alias, expected to fail.\n"
        "- `03_readback_ok.json`: expected and actual sketch snapshots match.\n"
        "- `04_readback_bad_geometry.json`: `right_root` is shifted, expected to fail readback.\n"
        "- `summary.json`: compact index of the generated result files.\n",
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
