"""Layer 2 nominal geometry for straight bevel gears (no COM).

The module follows ГОСТ 19624-74 macro geometry with the classic Tredgold
construction: the tooth space of the equivalent (virtual) spur gear on the back
cone is projected to the gear apex. The virtual tooth count
``z_v = z / cos delta`` is continuous; only the flank generator is shared with
the cylindrical module, while the projection and the CAD sections build the
conical envelope explicitly.

Representation mode is ``nominal``: the flanks are the Tredgold projection of a
sharp-rack generated virtual involute, not an exact spherical involute or an
octoid generated by a real bevel cutter. Root and tip surfaces of the CAD
solid are the circular face/root cones of the blank; the tooth-space cone is
truncated by the blank, exactly as documented in ``docs/gear-bevel.md``.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

from .basic_racks import resolve_rack
from .involute import build_tooth_space_flank, error_item, warning_item
from .measure import chordal_tooth, constant_chord
from .modules import describe_module

_EPS = 1e-12
K_BE_DEFAULT = 0.285
K_BE_LIMIT = 0.3
K_BE_MIN = 0.25
CAP_OVERSHOOT_MM = 1.0
SECTION_MARGIN_FRACTION = 0.08
SECTION_MARGIN_MIN_MM = 0.2
SECTION_MARGIN_MAX_MM = 1.0


def _polar(radius: float, angle: float) -> list[float]:
    """Planar point [Y, Z] at polar angle counted from +Z toward +Y."""
    return [radius * math.sin(angle), radius * math.cos(angle)]


def _radius(point: list[float]) -> float:
    return math.hypot(float(point[0]), float(point[1]))


def _theta(point: list[float]) -> float:
    """Polar angle of [Y, Z] counted from +Z toward +Y."""
    return math.atan2(float(point[0]), float(point[1]))


def _rotate(point: list[float], angle: float) -> list[float]:
    cosine, sine = math.cos(angle), math.sin(angle)
    return [
        float(point[0]) * cosine + float(point[1]) * sine,
        float(point[1]) * cosine - float(point[0]) * sine,
    ]


def _mirror(point: list[float]) -> list[float]:
    return [-float(point[0]), float(point[1])]


def _dedupe(points: list[list[float]], tolerance: float = 1e-9) -> list[list[float]]:
    unique: list[list[float]] = []
    for point in points:
        candidate = [float(point[0]), float(point[1])]
        if not unique or math.dist(unique[-1], candidate) > tolerance:
            unique.append(candidate)
    return unique


def _signed_area(polygon: list[list[float]]) -> float:
    area = 0.0
    for index in range(len(polygon) - 1):
        x1, y1 = polygon[index]
        x2, y2 = polygon[index + 1]
        area += x1 * y2 - x2 * y1
    return area / 2.0


def _clip_to_circle(polygon: list[list[float]], radius: float, segments: int = 720) -> list[list[float]]:
    """Sutherland-Hodgman clip of a closed polygon to a circle polygon."""
    clip = [
        [radius * math.sin(2.0 * math.pi * index / segments),
         radius * math.cos(2.0 * math.pi * index / segments)]
        for index in range(segments)
    ]

    def inside(point: list[float], a: list[float], b: list[float]) -> bool:
        return (b[0] - a[0]) * (point[1] - a[1]) - (b[1] - a[1]) * (point[0] - a[0]) <= 1e-12

    def intersect(p: list[float], q: list[float], a: list[float], b: list[float]) -> list[float]:
        denominator = (p[0] - q[0]) * (a[1] - b[1]) - (p[1] - q[1]) * (a[0] - b[0])
        if abs(denominator) < 1e-15:
            return [q[0], q[1]]
        px = ((p[0] * q[1] - p[1] * q[0]) * (a[0] - b[0]) - (p[0] - q[0]) * (a[0] * b[1] - a[1] * b[0])) / denominator
        py = ((p[0] * q[1] - p[1] * q[0]) * (a[1] - b[1]) - (p[1] - q[1]) * (a[0] * b[1] - a[1] * b[0])) / denominator
        return [px, py]

    output = [list(point) for point in polygon]
    for index in range(len(clip)):
        a = clip[index]
        b = clip[(index + 1) % len(clip)]
        if not output:
            break
        source = output
        output = []
        start = source[-1]
        for end in source:
            if inside(end, a, b):
                if not inside(start, a, b):
                    output.append(intersect(start, end, a, b))
                output.append(end)
            elif inside(start, a, b):
                output.append(intersect(start, end, a, b))
            start = end
    return output


def _polygon_area(points: list[list[float]]) -> float:
    return abs(_signed_area(points)) if len(points) >= 3 else 0.0


def _polygon_bounds(points: list[list[float]]) -> list[float]:
    first = [float(point[0]) for point in points]
    second = [float(point[1]) for point in points]
    return [min(first), min(second), max(first), max(second)]


def _involute(value: float) -> float:
    return math.tan(value) - value


@dataclass
class BevelGearGeometry:
    request: dict
    rack: object
    module_mm: float
    tooth_count: int
    pressure_angle_rad: float
    profile_shift: float
    face_width_mm: float
    face_width_source: str
    pitch_cone_angle_rad: float
    face_cone_angle_rad: float
    root_cone_angle_rad: float
    addendum_angle_rad: float
    dedendum_angle_rad: float
    outer_pitch_diameter_mm: float
    outer_cone_distance_mm: float
    inner_cone_distance_mm: float
    mean_cone_distance_mm: float
    outer_addendum_mm: float
    outer_dedendum_mm: float
    outer_tip_diameter_mm: float
    outer_root_diameter_mm: float
    apex_to_back_mm: float
    apex_to_inner_mm: float
    back_radius_mm: float
    inner_radius_mm: float
    axial_length_mm: float
    virtual_pitch_radius_mm: float
    virtual_tooth_count: float
    virtual_base_radius_mm: float
    virtual_tip_radius_mm: float
    virtual_root_radius_mm: float
    tooth_half_angle_rad: float
    base_half_angle_rad: float
    tip_half_angle_rad: float
    tooth_thickness_mm: float
    tip_arc_thickness_mm: float
    minimum_shift: float
    undercut: bool
    module_info: dict = field(default_factory=dict)
    virtual_surface_path: list[list[float]] = field(default_factory=list)
    virtual_surface_split_index: int = 0
    virtual_gap_outline: list[list[float]] = field(default_factory=list)
    end_view_period: list[list[float]] = field(default_factory=list)
    end_view_wheel: list[list[float]] = field(default_factory=list)
    back_face_gap: list[list[float]] = field(default_factory=list)
    section_outer: dict = field(default_factory=dict)
    section_inner: dict = field(default_factory=dict)
    expected_volume_mm3: float = 0.0
    blank_volume_mm3: float = 0.0
    removed_volume_mm3: float = 0.0
    expected_bounds_mm: list[float] = field(default_factory=list)
    warnings: list[dict] = field(default_factory=list)
    errors: list[dict] = field(default_factory=list)
    diagnostics: dict = field(default_factory=dict)


def _project_uv(x_plane: float, u: float, v: float, *, apex_x: float, sin_delta: float, cos_delta: float) -> list[float]:
    """Central projection of a virtual-plane point onto the frontal plane x=x_plane.

    The virtual back-cone plane is spanned by e1 = (sin d, 0, cos d) through
    e2 = (0, -1, 0); the section coordinate pair is [Y, Z] as in the other gear
    modules. The gap centre therefore sits on +Z.
    """
    point_x = apex_x + v * sin_delta
    scale = x_plane / point_x
    return [scale * (-u), scale * (v * cos_delta)]


def _section_samples(geometry: BevelGearGeometry, x_plane: float) -> dict:
    """Sampled frontal cross-section of the tooth-space cone at x=x_plane."""
    apex_x = -geometry.outer_cone_distance_mm / math.cos(geometry.pitch_cone_angle_rad)
    sin_delta = math.sin(geometry.pitch_cone_angle_rad)
    cos_delta = math.cos(geometry.pitch_cone_angle_rad)

    def project(u: float, v: float) -> list[float]:
        return _project_uv(x_plane, u, v, apex_x=apex_x, sin_delta=sin_delta, cos_delta=cos_delta)

    surface = geometry.virtual_surface_path
    split_index = geometry.virtual_surface_split_index
    root_path = [project(point[0], point[1]) for point in surface[: split_index + 1]]
    involute_path = [project(point[0], point[1]) for point in surface[split_index:]]
    tip_point = surface[-1]
    tip_angle = math.atan2(float(tip_point[0]), float(tip_point[1]))
    overshoot = geometry.virtual_tip_radius_mm + max(
        CAP_OVERSHOOT_MM, 0.02 * geometry.virtual_tip_radius_mm
    )
    cap_steps = max(8, int(12 * max(abs(tip_angle), 1e-3) / 0.1))
    tip_flat = project(float(tip_point[0]), float(tip_point[1]))
    cap_points = [
        tip_flat,
        *[
            project(*_polar(overshoot, tip_angle + (-2.0 * tip_angle) * index / cap_steps))
            for index in range(cap_steps + 1)
        ],
        [-tip_flat[0], tip_flat[1]],
    ]
    return {
        "x_mm": x_plane,
        "root_path": _dedupe(root_path, tolerance=1e-9),
        "involute_path": _dedupe(involute_path, tolerance=1e-9),
        "cap_points": _dedupe(cap_points, tolerance=1e-9),
        "surface_path": _dedupe([*root_path, *involute_path[1:]], tolerance=1e-9),
        "split_point": project(float(surface[split_index][0]), float(surface[split_index][1])),
        "tip_point": project(float(tip_point[0]), float(tip_point[1])),
    }


def build_bevel_gear_geometry(
    request: dict,
    *,
    curve_samples: int = 260,
) -> BevelGearGeometry:
    """Build the complete nominal geometry for one straight bevel gear."""
    rack = resolve_rack(
        str(request.get("standard") or "gost_13754_68"),
        str(request.get("modification") or "standard"),
        pressure_angle_deg=request.get("pressure_angle_deg"),
        addendum_coefficient=request.get("addendum_coefficient"),
        clearance_coefficient=request.get("clearance_coefficient"),
        root_fillet_coefficient=request.get("root_fillet_coefficient"),
    )
    module = float(request["module_mm"])
    tooth_count = int(request["tooth_count"])
    alpha = math.radians(float(rack.pressure_angle_deg))
    shift = float(request.get("profile_shift", 0.0))
    delta = math.radians(float(request.get("pitch_cone_angle_deg", 45.0)))
    sin_delta, cos_delta = math.sin(delta), math.cos(delta)
    ha = float(rack.addendum_coefficient)
    clearance = float(rack.clearance_coefficient)

    warnings: list[dict] = []
    errors: list[dict] = []

    outer_pitch_diameter = module * tooth_count
    outer_cone_distance = outer_pitch_diameter / (2.0 * sin_delta)
    outer_addendum = (ha + shift) * module
    outer_dedendum = (ha + clearance - shift) * module
    addendum_angle = math.atan(outer_addendum / outer_cone_distance)
    dedendum_angle = math.atan(outer_dedendum / outer_cone_distance)
    face_cone_angle = delta + addendum_angle
    root_cone_angle = delta - dedendum_angle
    outer_tip_diameter = outer_pitch_diameter + 2.0 * outer_addendum * cos_delta
    outer_root_diameter = outer_pitch_diameter - 2.0 * outer_dedendum * cos_delta
    apex_to_back = outer_cone_distance * cos_delta - outer_addendum * sin_delta
    back_radius = apex_to_back * math.tan(face_cone_angle)

    requested_width = request.get("face_width_mm")
    if requested_width is None or float(requested_width) <= 0.0:
        face_width = K_BE_DEFAULT * outer_cone_distance
        face_width_source = "gost_19624_recommendation_0.285_Re"
    else:
        face_width = float(requested_width)
        face_width_source = "explicit"
    axial_length = face_width * cos_delta
    apex_to_inner = apex_to_back - axial_length
    inner_radius = apex_to_inner * math.tan(face_cone_angle) if apex_to_inner > 0.0 else 0.0
    inner_cone_distance = outer_cone_distance - face_width
    mean_cone_distance = outer_cone_distance - 0.5 * face_width

    virtual_pitch_radius = outer_cone_distance * math.tan(delta)
    virtual_tooth_count = tooth_count / cos_delta
    virtual_base_radius = virtual_pitch_radius * math.cos(alpha)
    virtual_tip_radius = virtual_pitch_radius + outer_addendum
    virtual_root_radius = virtual_pitch_radius - outer_dedendum
    tooth_half_angle = (math.pi / 2.0 + 2.0 * shift * math.tan(alpha)) * cos_delta / tooth_count
    base_half_angle = math.pi * cos_delta / tooth_count - tooth_half_angle
    tooth_thickness = 2.0 * virtual_pitch_radius * tooth_half_angle
    tip_alpha = math.acos(
        min(1.0, max(-1.0, virtual_base_radius / max(virtual_tip_radius, _EPS)))
    ) if virtual_tip_radius > virtual_base_radius else 0.0
    tip_half_angle = (
        tooth_half_angle + _involute(alpha) - _involute(tip_alpha)
        if virtual_tip_radius > virtual_base_radius else 0.0
    )
    tip_arc_thickness = 2.0 * virtual_tip_radius * tip_half_angle
    minimum_shift = ha - virtual_tooth_count * math.sin(alpha) ** 2 / 2.0
    undercut = shift < minimum_shift - 1e-9

    module_info = describe_module(module, rack.module_system)
    if not module_info["standard_value"]:
        warnings.append(
            warning_item(
                "gear_module_off_row",
                "Module %g mm is outside the %s rows." % (module, module_info["standard_edition"]),
                module_mm=module,
                standard_edition=module_info["standard_edition"],
            )
        )
    below_range = rack.module_min is not None and module < rack.module_min - 1e-9
    above_range = rack.module_max is not None and (
        module >= rack.module_max - 1e-9
        if rack.module_max_exclusive
        else module > rack.module_max + 1e-9
    )
    if below_range or above_range:
        warnings.append(
            warning_item(
                "gear_standard_module_range",
                "Module %g mm is outside the applicable range of %s."
                % (module, rack.standard_edition),
                module_mm=module,
                standard=rack.standard_edition,
                module_min=rack.module_min,
                module_max=rack.module_max,
                module_max_exclusive=rack.module_max_exclusive,
            )
        )
    if not rack.conformity_claim:
        warnings.append(
            warning_item(
                "gear_contour_modified",
                "Explicit coefficients make this a user-defined rack without a standard-conformity claim.",
            )
        )
    warnings.append(
        warning_item(
            "gear_bevel_nominal_projection",
            (
                "Tredgold virtual-gear projection: nominal flanks, not an exact spherical "
                "involute and not an octoid generated by a real bevel cutter."
            ),
        )
    )
    if outer_tip_diameter <= 0.0 or outer_root_diameter <= 0.0:
        errors.append(
            error_item(
                "gear_bevel_invalid_diameters",
                "The outer root and tip diameters must be positive.",
                outer_tip_diameter_mm=outer_tip_diameter,
                outer_root_diameter_mm=outer_root_diameter,
            )
        )
    if outer_root_diameter >= outer_tip_diameter - _EPS:
        errors.append(
            error_item(
                "gear_bevel_invalid_radii",
                "The outer tip diameter must exceed the outer root diameter.",
                outer_tip_diameter_mm=outer_tip_diameter,
                outer_root_diameter_mm=outer_root_diameter,
            )
        )
    if face_cone_angle >= math.radians(89.5):
        errors.append(
            error_item(
                "gear_bevel_face_cone_degenerate",
                "The face cone is almost a plane; reduce the cone angle or the addendum.",
                face_cone_angle_deg=math.degrees(face_cone_angle),
            )
        )
    width_limit = K_BE_LIMIT * outer_cone_distance
    if face_width > width_limit + 1e-9:
        warnings.append(
            warning_item(
                "gear_bevel_face_width_above_recommendation",
                "Face width exceeds the ГОСТ 19624-74 recommendation K_be <= 0.3 R_e.",
                face_width_mm=face_width,
                limit_mm=width_limit,
                ratio=face_width / outer_cone_distance,
            )
        )
    if face_width >= inner_cone_distance - _EPS:
        errors.append(
            error_item(
                "gear_bevel_face_width_exceeds_cone",
                "Face width must stay below the outer cone distance.",
                face_width_mm=face_width,
                outer_cone_distance_mm=outer_cone_distance,
            )
        )
    if apex_to_inner <= 1e-6:
        errors.append(
            error_item(
                "gear_bevel_inner_face_not_positive",
                "The inner face plane reaches the apex; reduce the face width.",
                apex_to_inner_mm=apex_to_inner,
            )
        )
    if virtual_tip_radius <= virtual_base_radius + 1e-9:
        errors.append(
            error_item(
                "gear_bevel_tip_below_base",
                "The virtual tip circle does not reach the virtual base circle.",
                virtual_tip_radius_mm=virtual_tip_radius,
                virtual_base_radius_mm=virtual_base_radius,
            )
        )
    if tip_arc_thickness <= 0.0:
        errors.append(
            error_item(
                "gear_bevel_tip_thickness_negative",
                "The virtual involute flanks cross before the tip circle; the tooth tip is not constructible.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    elif tip_arc_thickness < 0.25 * module:
        warnings.append(
            warning_item(
                "gear_bevel_tip_thickness_low",
                "Tooth tip thickness is below 0.25 m; the flank may be pointed and sensitive to tolerances.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    elif tip_arc_thickness < 0.3 * module:
        warnings.append(
            warning_item(
                "gear_bevel_tip_thickness_below_recommendation",
                "Tooth tip thickness is below the 0.30 m recommendation.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    if undercut:
        warnings.append(
            warning_item(
                "gear_bevel_undercut",
                "The sharp rack cuts into the virtual involute near the base circle.",
                profile_shift=shift,
                minimum_shift=minimum_shift,
                virtual_tooth_count=virtual_tooth_count,
            )
        )

    geometry = BevelGearGeometry(
        request=dict(request),
        rack=rack,
        module_mm=module,
        tooth_count=tooth_count,
        pressure_angle_rad=alpha,
        profile_shift=shift,
        face_width_mm=face_width,
        face_width_source=face_width_source,
        pitch_cone_angle_rad=delta,
        face_cone_angle_rad=face_cone_angle,
        root_cone_angle_rad=root_cone_angle,
        addendum_angle_rad=addendum_angle,
        dedendum_angle_rad=dedendum_angle,
        outer_pitch_diameter_mm=outer_pitch_diameter,
        outer_cone_distance_mm=outer_cone_distance,
        inner_cone_distance_mm=inner_cone_distance,
        mean_cone_distance_mm=mean_cone_distance,
        outer_addendum_mm=outer_addendum,
        outer_dedendum_mm=outer_dedendum,
        outer_tip_diameter_mm=outer_tip_diameter,
        outer_root_diameter_mm=outer_root_diameter,
        apex_to_back_mm=apex_to_back,
        apex_to_inner_mm=apex_to_inner,
        back_radius_mm=back_radius,
        inner_radius_mm=inner_radius,
        axial_length_mm=axial_length,
        virtual_pitch_radius_mm=virtual_pitch_radius,
        virtual_tooth_count=virtual_tooth_count,
        virtual_base_radius_mm=virtual_base_radius,
        virtual_tip_radius_mm=virtual_tip_radius,
        virtual_root_radius_mm=virtual_root_radius,
        tooth_half_angle_rad=tooth_half_angle,
        base_half_angle_rad=base_half_angle,
        tip_half_angle_rad=tip_half_angle,
        tooth_thickness_mm=tooth_thickness,
        tip_arc_thickness_mm=tip_arc_thickness,
        minimum_shift=minimum_shift,
        undercut=undercut,
        module_info=module_info,
        warnings=warnings,
        errors=errors,
    )
    if errors:
        return geometry

    flank = build_tooth_space_flank(
        pitch_radius=virtual_pitch_radius,
        base_radius=virtual_base_radius,
        outside_radius=virtual_tip_radius,
        root_radius=virtual_root_radius,
        module_mm=module,
        pressure_angle_rad=alpha,
        base_half_angle_rad=base_half_angle,
        rack_depth_mm=(ha + clearance) * module,
        corner_depth_mm=(ha + clearance - shift) * module,
        curve_samples=curve_samples,
    )
    if flank.get("errors"):
        geometry.errors = list(flank["errors"])
        return geometry

    surface = flank["surface"]
    geometry.virtual_surface_path = surface
    geometry.virtual_surface_split_index = int(flank["surface_split_index"])
    tip_point = surface[-1]
    tip_angle = math.atan2(float(tip_point[0]), float(tip_point[1]))
    overshoot = virtual_tip_radius + max(CAP_OVERSHOOT_MM, 0.02 * virtual_tip_radius)
    cap_steps = max(8, int(12 * max(abs(tip_angle), 1e-3) / 0.1))
    cap_arc = [
        _polar(overshoot, tip_angle + (-2.0 * tip_angle) * index / cap_steps)
        for index in range(cap_steps + 1)
    ]
    mirrored_surface = [[-point[0], point[1]] for point in reversed(surface)]
    virtual_gap = _dedupe([*surface, *cap_arc, *mirrored_surface[1:], [float(surface[0][0]), float(surface[0][1])]])
    if _signed_area(virtual_gap) < 0.0:
        virtual_gap = list(reversed(virtual_gap))
    geometry.virtual_gap_outline = virtual_gap

    apex_x = -outer_cone_distance / cos_delta
    max_point_x = max(apex_x + float(point[1]) * sin_delta for point in virtual_gap)
    if max_point_x > -max(1e-3, 1e-4 * outer_cone_distance):
        geometry.errors.append(
            error_item(
                "gear_bevel_apex_projection_invalid",
                "A virtual profile point reaches the apex plane; the conical projection is not finite.",
                max_virtual_x_mm=max_point_x,
                apex_x_mm=apex_x,
            )
        )
        return geometry

    # Back-face (end view) geometry: project the tooth-space cone to the outer
    # back plane and clip it by the face-cone disc of radius R_ao = B tan(dA).
    def project_back(u: float, v: float) -> list[float]:
        return _project_uv(
            -apex_to_back, u, v,
            apex_x=apex_x, sin_delta=sin_delta, cos_delta=cos_delta,
        )

    back_gap = [project_back(point[0], point[1]) for point in virtual_gap]
    geometry.back_face_gap = _clip_to_circle(back_gap, back_radius, segments=360)

    # Material period from one gap centre to the next: the projected right
    # flank, the radial cap extension and cap out to the face-cone crossing,
    # the tip arc, and the mirrored boundary of the next gap.
    surface_back = [project_back(point[0], point[1]) for point in surface]
    cap_back = [project_back(point[0], point[1]) for point in cap_arc]
    right_boundary = [*surface_back, *cap_back]
    right_crossing = None
    for index in range(len(right_boundary) - 1):
        current = right_boundary[index]
        following = right_boundary[index + 1]
        current_radius = _radius(current)
        following_radius = _radius(following)
        if current_radius <= back_radius < following_radius:
            span = following_radius - current_radius
            factor = (back_radius - current_radius) / span if span > 1e-15 else 0.0
            right_crossing = (
                index,
                [
                    current[0] + (following[0] - current[0]) * factor,
                    current[1] + (following[1] - current[1]) * factor,
                ],
            )
            break
    if right_crossing is None:
        geometry.errors.append(
            error_item(
                "gear_bevel_back_face_crossing_missing",
                "The projected tooth space does not cross the back-face tip circle.",
                back_radius_mm=back_radius,
            )
        )
        return geometry
    crossing_index, crossing = right_crossing
    crossing_angle = _theta(crossing)
    pitch_angle = 2.0 * math.pi / tooth_count
    inner_surface = [*right_boundary[: crossing_index + 1], crossing]
    tip_arc_span = pitch_angle - 2.0 * crossing_angle
    tip_arc_steps = max(4, int(16 * max(abs(tip_arc_span), 1e-3) / 0.1))
    tip_arc = [
        _polar(back_radius, crossing_angle + tip_arc_span * step / tip_arc_steps)
        for step in range(tip_arc_steps + 1)
    ]
    mirrored_tooth = [
        _rotate(_mirror(point), pitch_angle) for point in reversed(inner_surface)
    ]
    period = _dedupe([*inner_surface, *tip_arc[1:-1], *mirrored_tooth[1:]])
    if math.dist(period[0], period[-1]) > 1e-9:
        period.append(period[0])
    geometry.end_view_period = period
    wheel: list[list[float]] = []
    for index in range(tooth_count):
        rotated = [_rotate(point, index * pitch_angle) for point in period]
        if wheel:
            rotated = rotated[1:]
        wheel.extend(rotated)
    wheel = _dedupe(wheel)
    if math.dist(wheel[0], wheel[-1]) > 1e-9:
        wheel.append(wheel[0])
    geometry.end_view_wheel = wheel

    # CAD sections: exact frontal cross-sections of the tooth-space cone. The
    # inner section is the central scaling of the outer one, so a two-section
    # loft follows the projection rays exactly.
    margin = min(
        SECTION_MARGIN_MAX_MM,
        max(SECTION_MARGIN_MIN_MM, SECTION_MARGIN_FRACTION * face_width),
    )
    x_outer = -(apex_to_back + margin)
    x_inner = -(apex_to_inner - margin)
    if x_inner >= -margin:
        geometry.errors.append(
            error_item(
                "gear_bevel_inner_section_invalid",
                "The inner section plane reaches the apex with the CAD margin applied.",
                x_inner_mm=x_inner,
            )
        )
        return geometry
    geometry.section_outer = _section_samples(geometry, x_outer)
    inner_scale = x_inner / x_outer
    outer = geometry.section_outer
    geometry.section_inner = {
        "x_mm": x_inner,
        "scale": inner_scale,
        "root_path": [[point[0] * inner_scale, point[1] * inner_scale] for point in outer["root_path"]],
        "involute_path": [[point[0] * inner_scale, point[1] * inner_scale] for point in outer["involute_path"]],
        "cap_points": [[point[0] * inner_scale, point[1] * inner_scale] for point in outer["cap_points"]],
        "surface_path": [[point[0] * inner_scale, point[1] * inner_scale] for point in outer["surface_path"]],
        "split_point": [outer["split_point"][0] * inner_scale, outer["split_point"][1] * inner_scale],
        "tip_point": [outer["tip_point"][0] * inner_scale, outer["tip_point"][1] * inner_scale],
    }
    geometry.diagnostics = {
        "curves": flank,
        "back_gap_area_mm2": _polygon_area(geometry.back_face_gap),
        "section_margin_mm": margin,
        "inner_section_scale": inner_scale,
    }

    # Expected body volume: the blank cone frustum minus z tooth spaces. Every
    # frontal tooth-space section is the central scaling of the clipped back
    # section, so the integral has a closed cubic form.
    blank_volume = (math.pi / 3.0) * math.tan(face_cone_angle) ** 2 * (
        apex_to_back ** 3 - apex_to_inner ** 3
    )
    back_gap_area = _polygon_area(geometry.back_face_gap)
    removed_one = back_gap_area * (
        apex_to_back ** 3 - apex_to_inner ** 3
    ) / (3.0 * apex_to_back ** 2)
    geometry.blank_volume_mm3 = blank_volume
    geometry.removed_volume_mm3 = tooth_count * removed_one
    geometry.expected_volume_mm3 = blank_volume - tooth_count * removed_one
    y_values = [point[0] for point in geometry.end_view_wheel]
    z_values = [point[1] for point in geometry.end_view_wheel]
    geometry.expected_bounds_mm = [
        -apex_to_back, min(y_values), min(z_values),
        -apex_to_inner, max(y_values), max(z_values),
    ]
    if geometry.expected_volume_mm3 <= 0.0 or not math.isfinite(geometry.expected_volume_mm3):
        geometry.errors.append(
            error_item(
                "gear_bevel_expected_volume_not_positive",
                "The expected bevel-gear volume is not positive.",
                expected_volume_mm3=geometry.expected_volume_mm3,
            )
        )
    return geometry


def evaluate_bevel_gear_checks(geometry: BevelGearGeometry, measurements: dict) -> dict:
    """Combine scalar diagnostics and control measurements into one report."""
    checks: list[dict] = []

    def check(code, status, message, *, value=None, limit=None, unit=None):
        checks.append(
            {
                "code": code,
                "status": status,
                "message": message,
                "value": value,
                "limit": limit,
                "unit": unit,
            }
        )

    check(
        "gear_bevel_cone_angles",
        "ok" if 5.0 <= math.degrees(geometry.pitch_cone_angle_rad) <= 85.0 else "error",
        "Pitch cone angle against the ГОСТ 19624-74 range 5..85 degrees.",
        value=math.degrees(geometry.pitch_cone_angle_rad),
        limit=[5.0, 85.0],
        unit="deg",
    )
    check(
        "gear_bevel_face_cone",
        "ok" if geometry.face_cone_angle_rad < math.radians(89.5) else "error",
        "Face cone angle stays below the degenerate flat-cone limit.",
        value=math.degrees(geometry.face_cone_angle_rad),
        limit=89.5,
        unit="deg",
    )
    diameter_order_ok = (
        0.0 < geometry.outer_root_diameter_mm < geometry.outer_pitch_diameter_mm < geometry.outer_tip_diameter_mm
    )
    check(
        "gear_bevel_radii",
        "ok" if diameter_order_ok else "error",
        "Outer root, pitch and tip diameters are ordered and positive.",
        value={
            "root_diameter_mm": geometry.outer_root_diameter_mm,
            "pitch_diameter_mm": geometry.outer_pitch_diameter_mm,
            "tip_diameter_mm": geometry.outer_tip_diameter_mm,
        },
    )
    check(
        "gear_bevel_face_width",
        "warning" if geometry.face_width_mm > K_BE_LIMIT * geometry.outer_cone_distance_mm + 1e-9 else "ok",
        "Functional face width against the ГОСТ 19624-74 recommendation K_be <= 0.3 R_e.",
        value=geometry.face_width_mm,
        limit=K_BE_LIMIT * geometry.outer_cone_distance_mm,
        unit="mm",
    )
    check(
        "gear_bevel_inner_face",
        "ok" if geometry.apex_to_inner_mm > 0.0 else "error",
        "Apex distance of the inner face plane stays positive.",
        value=geometry.apex_to_inner_mm,
        limit=0.0,
        unit="mm",
    )
    tip_value = geometry.tip_arc_thickness_mm
    if tip_value <= 0.0:
        tip_status = "error"
    elif tip_value < 0.25 * geometry.module_mm:
        tip_status = "warning"
    elif tip_value < 0.3 * geometry.module_mm:
        tip_status = "warning"
    else:
        tip_status = "ok"
    check(
        "gear_bevel_tip_thickness",
        tip_status,
        "Virtual tip circle tooth thickness against the 0.30 m recommendation.",
        value=tip_value,
        limit=0.3 * geometry.module_mm,
        unit="mm",
    )
    check(
        "gear_bevel_virtual_undercut",
        "warning" if geometry.undercut else "ok",
        "Sharp-rack undercut of the Tredgold virtual gear.",
        value=geometry.profile_shift,
        limit=geometry.minimum_shift,
        unit="coefficient",
    )
    check(
        "gear_bevel_virtual_gear",
        "ok",
        "Continuous Tredgold virtual gear parameters used for the flank.",
        value={
            "virtual_tooth_count": geometry.virtual_tooth_count,
            "virtual_pitch_diameter_mm": 2.0 * geometry.virtual_pitch_radius_mm,
            "virtual_tip_diameter_mm": 2.0 * geometry.virtual_tip_radius_mm,
            "virtual_root_diameter_mm": 2.0 * geometry.virtual_root_radius_mm,
        },
    )
    module_status = "ok" if geometry.module_info.get("standard_value") else "warning"
    check(
        "gear_module_row",
        module_status,
        "Module value against %s rows and their recorded exceptions."
        % geometry.module_info.get("standard_edition"),
        value=geometry.module_mm,
        unit="mm",
    )
    check(
        "gear_bevel_representation",
        "warning",
        (
            "Representation mode is nominal: the flank is the Tredgold projection of a "
            "sharp-rack virtual involute, not the exact spherical involute or an octoid."
        ),
    )
    failed = [item for item in checks if item["status"] == "error"]
    warnings = [item for item in checks if item["status"] == "warning"]
    return {
        "status": "error" if failed else ("warning" if warnings else "ok"),
        "checks": checks,
        "errors": failed,
        "warnings": warnings,
        "representation_mode": "nominal",
        "conformity_claim": False,
    }


def build_bevel_gear_preview(
    request: dict,
    *,
    wheel_points_per_tooth: int = 48,
) -> dict:
    """Validate the request and return the complete nominal analysis."""
    geometry = build_bevel_gear_geometry(request)
    warning_items = list(geometry.warnings)
    warnings = [str(item["message"]) for item in warning_items]
    if geometry.errors:
        return {
            "success": False,
            "family": "gear_bevel",
            "request": dict(request),
            "warnings": warnings,
            "warning_items": warning_items,
            "errors": list(geometry.errors),
            "report": {
                "status": "error",
                "checks": [],
                "errors": list(geometry.errors),
                "representation_mode": "nominal",
                "conformity_claim": False,
            },
            "geometry": {},
            "derived": {},
            "measurements": {},
        }

    module = geometry.module_mm
    constant = constant_chord(
        module_mm=module,
        profile_shift=geometry.profile_shift,
        pressure_angle_rad=geometry.pressure_angle_rad,
        pitch_radius=geometry.virtual_pitch_radius_mm,
        outside_radius=geometry.virtual_tip_radius_mm,
    )
    chordal = chordal_tooth(
        pitch_radius=geometry.virtual_pitch_radius_mm,
        tooth_thickness_mm=geometry.tooth_thickness_mm,
    )
    measurements = {
        "outer_tooth_thickness_mm": geometry.tooth_thickness_mm,
        "virtual_tooth_count": geometry.virtual_tooth_count,
        "constant_chord_mm": constant["constant_chord_mm"],
        "constant_chord_height_mm": constant["constant_chord_height_mm"],
        "chordal_tooth_thickness_mm": chordal["chordal_tooth_thickness_mm"],
        "chordal_height_mm": chordal["chordal_height_mm"],
        "tip_thickness_mm": geometry.tip_arc_thickness_mm,
        "base_pitch_mm": math.pi * module * math.cos(geometry.pressure_angle_rad),
    }
    report = evaluate_bevel_gear_checks(geometry, measurements)
    summary = {
        "tooth_type": "straight",
        "module_mm": module,
        "tooth_count": geometry.tooth_count,
        "standard": geometry.rack.standard,
        "modification": geometry.rack.modification,
        "contour_name": geometry.rack.name_ru,
        "standard_edition": geometry.rack.standard_edition,
        "pressure_angle_deg": math.degrees(geometry.pressure_angle_rad),
        "profile_shift": geometry.profile_shift,
        "face_width_mm": geometry.face_width_mm,
        "face_width_source": geometry.face_width_source,
        "pitch_cone_angle_deg": math.degrees(geometry.pitch_cone_angle_rad),
        "face_cone_angle_deg": math.degrees(geometry.face_cone_angle_rad),
        "root_cone_angle_deg": math.degrees(geometry.root_cone_angle_rad),
        "addendum_angle_deg": math.degrees(geometry.addendum_angle_rad),
        "dedendum_angle_deg": math.degrees(geometry.dedendum_angle_rad),
        "outer_pitch_diameter_mm": geometry.outer_pitch_diameter_mm,
        "outer_tip_diameter_mm": geometry.outer_tip_diameter_mm,
        "outer_root_diameter_mm": geometry.outer_root_diameter_mm,
        "outer_cone_distance_mm": geometry.outer_cone_distance_mm,
        "inner_cone_distance_mm": geometry.inner_cone_distance_mm,
        "mean_cone_distance_mm": geometry.mean_cone_distance_mm,
        "outer_addendum_mm": geometry.outer_addendum_mm,
        "outer_dedendum_mm": geometry.outer_dedendum_mm,
        "apex_to_back_mm": geometry.apex_to_back_mm,
        "apex_to_inner_mm": geometry.apex_to_inner_mm,
        "axial_length_mm": geometry.axial_length_mm,
        "back_radius_mm": geometry.back_radius_mm,
        "inner_radius_mm": geometry.inner_radius_mm,
        "virtual_pitch_radius_mm": geometry.virtual_pitch_radius_mm,
        "virtual_tooth_count": geometry.virtual_tooth_count,
        "virtual_base_radius_mm": geometry.virtual_base_radius_mm,
        "virtual_tip_radius_mm": geometry.virtual_tip_radius_mm,
        "virtual_root_radius_mm": geometry.virtual_root_radius_mm,
        "tip_half_angle_deg": math.degrees(geometry.tip_half_angle_rad),
        "minimum_shift": geometry.minimum_shift,
        "undercut": geometry.undercut,
        "expected_volume_mm3": geometry.expected_volume_mm3,
        "representation_mode": report["representation_mode"],
        "verification_status": report["status"],
    }
    derived = {
        **summary,
        "module_row": geometry.module_info.get("row"),
        "module_status": geometry.module_info.get("status"),
        "checks": report["checks"],
    }
    return {
        "success": True,
        "family": "gear_bevel",
        "request": dict(request),
        "representation_mode": report["representation_mode"],
        "geometry": {
            "coordinate_system": "end_view_polar_yz",
            "end_view_period": geometry.end_view_period,
            "end_view_wheel": geometry.end_view_wheel,
            "back_face_gap": geometry.back_face_gap,
            "virtual_surface_path": geometry.virtual_surface_path,
            "virtual_gap_outline": geometry.virtual_gap_outline,
            "pitch_radius_mm": geometry.outer_pitch_diameter_mm / 2.0,
            "tip_radius_mm": geometry.back_radius_mm,
            "root_radius_mm": geometry.outer_root_diameter_mm / 2.0,
            "back_face_root_radius_mm": geometry.apex_to_back_mm * math.tan(geometry.root_cone_angle_rad),
            "inner_tip_radius_mm": geometry.inner_radius_mm,
            "axial_length_mm": geometry.axial_length_mm,
            "virtual_pitch_radius_mm": geometry.virtual_pitch_radius_mm,
            "virtual_tip_radius_mm": geometry.virtual_tip_radius_mm,
            "virtual_root_radius_mm": geometry.virtual_root_radius_mm,
            "axial_section": {
                "apex_to_back_mm": geometry.apex_to_back_mm,
                "apex_to_inner_mm": geometry.apex_to_inner_mm,
                "back_radius_mm": geometry.back_radius_mm,
                "inner_radius_mm": geometry.inner_radius_mm,
                "pitch_radius_back_mm": geometry.apex_to_back_mm * math.tan(geometry.pitch_cone_angle_rad),
                "pitch_radius_inner_mm": geometry.apex_to_inner_mm * math.tan(geometry.pitch_cone_angle_rad),
                "root_radius_back_mm": geometry.apex_to_back_mm * math.tan(geometry.root_cone_angle_rad),
                "root_radius_inner_mm": geometry.apex_to_inner_mm * math.tan(geometry.root_cone_angle_rad),
            },
            "section_outer_x_mm": geometry.section_outer.get("x_mm"),
            "section_inner_x_mm": geometry.section_inner.get("x_mm"),
        },
        "derived": derived,
        "measurements": measurements,
        "summary": summary,
        "report": report,
        "warnings": warnings,
        "warning_items": warning_items,
    }
