"""Layer 2 nominal geometry for straight bevel gears (no COM).

The module follows ГОСТ 19624-74 macro geometry with the classic Tredgold
construction: the tooth space of the equivalent (virtual) spur gear on the back
cone is projected to the gear apex. The virtual tooth count
``z_v = z / cos delta`` is continuous; only the flank generator is shared with
the cylindrical module, while the conical envelope is built explicitly.

The blank is a dish rather than a cone frustum: a flat base plate with two
conical end faces perpendicular to the tooth (the back cone at the outer end
and the front cone at the inner end) and the face cone between them. The tooth
space is cut between the same two cone planes, so the tooth ends are formed by
those conical faces and never look pointed.

Representation mode is ``nominal``: the flanks are the Tredgold projection of a
sharp-rack generated virtual involute, not an exact spherical involute or an
octoid generated by a real bevel cutter.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

from .basic_racks import resolve_rack
from .involute import build_tooth_space_flank, error_item, warning_item
from .measure import chordal_tooth, constant_chord
from .modules import describe_module

_EPS = 1e-12
K_BE_DEFAULT = 0.285
K_BE_LIMIT = 0.3
CAP_OVERSHOOT_MM = 1.0
SECTION_MARGIN_FRACTION = 0.08
SECTION_MARGIN_MIN_MM = 0.2
SECTION_MARGIN_MAX_MM = 2.0
RIM_BACK_EXTENSION_FRACTION = 1.2
RIM_BACK_EXTENSION_MIN_MM = 2.0
RIM_FRONT_EXTENSION_FRACTION = 0.3
RIM_FRONT_EXTENSION_MIN_MM = 1.5
AREA_INTEGRATION_STEPS = 720


def _polar(radius: float, angle: float) -> list[float]:
    """Planar point [Y, Z] at polar angle counted from +Z toward +Y."""
    return [radius * math.sin(angle), radius * math.cos(angle)]


def _radius(point: list[float]) -> float:
    return math.hypot(float(point[0]), float(point[1]))


def _theta(point: list[float]) -> float:
    """Polar angle of [Y, Z] counted from +Z toward +Y."""
    return math.atan2(float(point[0]), float(point[1]))


def _rotate(point: list[float], angle: float) -> list[float]:
    cosine, sine = math.cos(angle), math.sin(angle)
    return [
        float(point[0]) * cosine + float(point[1]) * sine,
        float(point[1]) * cosine - float(point[0]) * sine,
    ]


def _mirror(point: list[float]) -> list[float]:
    return [-float(point[0]), float(point[1])]


def _dedupe(points: list[list[float]], tolerance: float = 1e-9) -> list[list[float]]:
    unique: list[list[float]] = []
    for point in points:
        candidate = [float(point[0]), float(point[1])]
        if not unique or math.dist(unique[-1], candidate) > tolerance:
            unique.append(candidate)
    return unique


def _signed_area(polygon: list[list[float]]) -> float:
    area = 0.0
    for index in range(len(polygon) - 1):
        x1, y1 = polygon[index]
        x2, y2 = polygon[index + 1]
        area += x1 * y2 - x2 * y1
    return area / 2.0


def _polygon_area(points: list[list[float]]) -> float:
    return abs(_signed_area(points)) if len(points) >= 3 else 0.0


def _involute(value: float) -> float:
    return math.tan(value) - value


@dataclass
class BevelGearGeometry:
    request: dict
    rack: object
    module_mm: float
    tooth_count: int
    pressure_angle_rad: float
    profile_shift: float
    face_width_mm: float
    face_width_source: str
    pitch_cone_angle_rad: float
    face_cone_angle_rad: float
    root_cone_angle_rad: float
    addendum_angle_rad: float
    dedendum_angle_rad: float
    outer_pitch_diameter_mm: float
    outer_cone_distance_mm: float
    inner_cone_distance_mm: float
    mean_cone_distance_mm: float
    outer_addendum_mm: float
    outer_dedendum_mm: float
    outer_tip_diameter_mm: float
    outer_root_diameter_mm: float
    virtual_pitch_radius_mm: float
    virtual_tooth_count: float
    virtual_base_radius_mm: float
    virtual_tip_radius_mm: float
    virtual_root_radius_mm: float
    tooth_half_angle_rad: float
    base_half_angle_rad: float
    tip_half_angle_rad: float
    tooth_thickness_mm: float
    tip_arc_thickness_mm: float
    minimum_shift: float
    undercut: bool
    rim_back_extension_mm: float
    rim_front_extension_mm: float
    back_face_x_mm: float
    back_face_radius_mm: float
    front_face_x_mm: float
    front_face_radius_mm: float
    tip_corner_x_mm: float
    tip_corner_radius_mm: float
    inner_tip_corner_x_mm: float
    inner_tip_corner_radius_mm: float
    section_margin_mm: float
    section_outer_cone_distance_mm: float
    section_inner_cone_distance_mm: float
    module_info: dict = field(default_factory=dict)
    virtual_surface_path: list[list[float]] = field(default_factory=list)
    virtual_surface_split_index: int = 0
    virtual_gap_outline: list[list[float]] = field(default_factory=list)
    virtual_cap_points: list[list[float]] = field(default_factory=list)
    cone_frame: dict = field(default_factory=dict)
    blank_profile: list[list[float]] = field(default_factory=list)
    tooth_lines: dict = field(default_factory=dict)
    end_view_period: list[list[float]] = field(default_factory=list)
    end_view_wheel: list[list[float]] = field(default_factory=list)
    expected_volume_mm3: float = 0.0
    blank_volume_mm3: float = 0.0
    removed_volume_mm3: float = 0.0
    gap_area_clipped_mm2: float = 0.0
    expected_bounds_mm: list[float] = field(default_factory=list)
    warnings: list[dict] = field(default_factory=list)
    errors: list[dict] = field(default_factory=list)
    diagnostics: dict = field(default_factory=dict)


def _cone_line_radius(x_mm: float, pitch_point: list[float], cos_delta: float, sin_delta: float) -> float:
    """Radius on a cone-normal line through `pitch_point` at axial x."""
    return float(pitch_point[1]) + (float(x_mm) - float(pitch_point[0])) * cos_delta / sin_delta


def _revolution_volume(profile: list[list[float]]) -> float:
    """Volume of the solid of revolution of a closed (x, r) profile."""
    total = 0.0
    for index in range(len(profile) - 1):
        x1, r1 = float(profile[index][0]), float(profile[index][1])
        x2, r2 = float(profile[index + 1][0]), float(profile[index + 1][1])
        total += (x2 - x1) * (r1 * r1 + r1 * r2 + r2 * r2)
    return abs(math.pi / 3.0 * total)


def _project_to_end_view(point: list[float], cos_delta: float) -> list[float]:
    """Orthographic end view of a virtual-plane point: drop the gear-axis part."""
    return [-float(point[0]), float(point[1]) * cos_delta]


def _ray_polygon_intervals(
    origin: list[float],
    direction: list[float],
    polygon: list[list[float]],
) -> list[float]:
    """Positive ray parameters where the ray crosses the polygon boundary."""
    hits = []
    for index in range(len(polygon) - 1):
        ax, ay = float(polygon[index][0]), float(polygon[index][1])
        bx, by = float(polygon[index + 1][0]), float(polygon[index + 1][1])
        ex, ey = bx - ax, by - ay
        denominator = direction[0] * ey - direction[1] * ex
        if abs(denominator) < 1e-15:
            continue
        wx, wy = ax - origin[0], ay - origin[1]
        t = (wx * ey - wy * ex) / denominator
        u = (wx * direction[1] - wy * direction[0]) / denominator
        if t >= -1e-12 and -1e-9 <= u <= 1.0 + 1e-9:
            hits.append(max(0.0, t))
    hits.sort()
    return hits


def _clipped_gap_area(
    gap_outline: list[list[float]],
    *,
    cone_apex_x: float,
    sin_delta: float,
    cos_delta: float,
    tan_face_cone: float,
) -> float:
    """Area of the tooth-space region clipped by the blank's face cone.

    Kept as a single-station diagnostic at the back-cone plane.
    """
    arrays = _clipped_gap_ray_arrays(
        gap_outline,
        cone_apex_x=cone_apex_x,
        sin_delta=sin_delta,
        cos_delta=cos_delta,
        tan_face_cone=tan_face_cone,
    )
    if arrays is None:
        return 0.0
    angles, t_inner, t_outer, t_cone = arrays
    area = 0.0
    delta_angle = (angles[-1] - angles[0]) / max(1, len(angles) - 1)
    for index in range(len(angles)):
        lower = t_inner[index]
        upper = min(t_outer[index], t_cone[index]) if t_cone[index] > 0.0 else t_outer[index]
        if upper > lower:
            area += 0.5 * (upper * upper - lower * lower) * delta_angle
    return area


def _clipped_gap_ray_arrays(
    gap_outline: list[list[float]],
    *,
    cone_apex_x: float,
    sin_delta: float,
    cos_delta: float,
    tan_face_cone: float,
):
    """Per-ray gap interval [t_inner, t_outer] and face-cone bound t_cone."""
    if len(gap_outline) < 4:
        return None
    angles_raw = [math.atan2(point[1], point[0]) for point in gap_outline[:-1]]
    if not angles_raw:
        return None
    centre = math.pi / 2.0
    unwrapped = []
    for angle in angles_raw:
        value = angle
        while value - centre > math.pi:
            value -= 2.0 * math.pi
        while centre - value > math.pi:
            value += 2.0 * math.pi
        unwrapped.append(value)
    start, end = min(unwrapped), max(unwrapped)
    if end - start <= 1e-9:
        return None
    steps = AREA_INTEGRATION_STEPS
    angles = [start + (end - start) * (index + 0.5) / steps for index in range(steps + 1)]
    apex_distance = -cone_apex_x
    t_inner: list[float] = []
    t_outer: list[float] = []
    t_cone: list[float] = []
    for angle in angles:
        direction = [math.cos(angle), math.sin(angle)]
        hits = _ray_polygon_intervals([0.0, 0.0], direction, gap_outline)
        if len(hits) >= 2:
            t_inner.append(hits[0])
            t_outer.append(hits[1])
        else:
            t_inner.append(0.0)
            t_outer.append(0.0)
        sin_phi, cos_phi = direction[1], direction[0]
        quadratic_a = (
            cos_phi * cos_phi
            + cos_delta * cos_delta * sin_phi * sin_phi
            - tan_face_cone * tan_face_cone * sin_delta * sin_delta * sin_phi * sin_phi
        )
        quadratic_b = (
            2.0 * tan_face_cone * tan_face_cone * apex_distance * sin_delta * sin_phi
        )
        quadratic_c = tan_face_cone * tan_face_cone * apex_distance * apex_distance
        if abs(quadratic_a) <= 1e-12:
            t_cone.append(0.0)
            continue
        discriminant = quadratic_b * quadratic_b + 4.0 * quadratic_a * quadratic_c
        if discriminant < 0.0:
            t_cone.append(0.0)
            continue
        t_cone.append((-quadratic_b + math.sqrt(discriminant)) / (2.0 * quadratic_a))
    return angles, t_inner, t_outer, t_cone


def _removed_volume(
    gap_outline: list[list[float]],
    *,
    cone_apex_x: float,
    sin_delta: float,
    cos_delta: float,
    tan_face_cone: float,
    back_face_x: float,
    front_face_x: float,
    outer_cone_distance: float,
    inner_cone_distance: float,
    stations: int = 240,
) -> float:
    """Volume of one tooth space inside the dish blank.

    The tooth space is the cone over the virtual gap between the two cone
    planes. Each cone-normal station is clipped by the blank's face cone and by
    the flat back face (``x >= back_face_x``); the front cone plane bounds the
    station range, and the blank's rim overhang keeps the material on the
    ``R >= R_i`` side.
    """
    arrays = _clipped_gap_ray_arrays(
        gap_outline,
        cone_apex_x=cone_apex_x,
        sin_delta=sin_delta,
        cos_delta=cos_delta,
        tan_face_cone=tan_face_cone,
    )
    if arrays is None:
        return 0.0
    angles, t_inner, t_outer, t_cone = arrays
    delta_angle = (angles[-1] - angles[0]) / max(1, len(angles) - 1)
    delta_r = (outer_cone_distance - inner_cone_distance) / max(1, stations)
    volume = 0.0
    for station in range(stations):
        cone_distance = inner_cone_distance + delta_r * (station + 0.5)
        scale = cone_distance / outer_cone_distance
        back_limit = (back_face_x / scale - cone_apex_x) / sin_delta
        area = 0.0
        for index in range(len(angles)):
            sin_phi = math.sin(angles[index])
            lower = t_inner[index]
            upper = t_outer[index]
            if upper <= lower:
                continue
            if sin_phi > 1e-9:
                lower = max(lower, back_limit / sin_phi)
                if upper <= lower:
                    continue
            if t_cone[index] > 0.0:
                upper = min(upper, t_cone[index])
                if upper <= lower:
                    continue
            area += 0.5 * (upper * upper - lower * lower) * delta_angle
        volume += scale * scale * area * delta_r
    return volume


def build_bevel_gear_geometry(
    request: dict,
    *,
    curve_samples: int = 260,
) -> BevelGearGeometry:
    """Build the complete nominal geometry for one straight bevel gear."""
    rack = resolve_rack(
        str(request.get("standard") or "gost_13754_68"),
        str(request.get("modification") or "standard"),
        pressure_angle_deg=request.get("pressure_angle_deg"),
        addendum_coefficient=request.get("addendum_coefficient"),
        clearance_coefficient=request.get("clearance_coefficient"),
        root_fillet_coefficient=request.get("root_fillet_coefficient"),
    )
    module = float(request["module_mm"])
    tooth_count = int(request["tooth_count"])
    alpha = math.radians(float(rack.pressure_angle_deg))
    shift = float(request.get("profile_shift", 0.0))
    delta = math.radians(float(request.get("pitch_cone_angle_deg", 45.0)))
    sin_delta, cos_delta = math.sin(delta), math.cos(delta)
    ha = float(rack.addendum_coefficient)
    clearance = float(rack.clearance_coefficient)

    warnings: list[dict] = []
    errors: list[dict] = []

    outer_pitch_diameter = module * tooth_count
    outer_cone_distance = outer_pitch_diameter / (2.0 * sin_delta)
    outer_addendum = (ha + shift) * module
    outer_dedendum = (ha + clearance - shift) * module
    addendum_angle = math.atan(outer_addendum / outer_cone_distance)
    dedendum_angle = math.atan(outer_dedendum / outer_cone_distance)
    face_cone_angle = delta + addendum_angle
    root_cone_angle = delta - dedendum_angle
    outer_tip_diameter = outer_pitch_diameter + 2.0 * outer_addendum * cos_delta
    outer_root_diameter = outer_pitch_diameter - 2.0 * outer_dedendum * cos_delta

    requested_width = request.get("face_width_mm")
    if requested_width is None or float(requested_width) <= 0.0:
        face_width = K_BE_DEFAULT * outer_cone_distance
        face_width_source = "gost_19624_recommendation_0.285_Re"
    else:
        face_width = float(requested_width)
        face_width_source = "explicit"
    inner_cone_distance = outer_cone_distance - face_width
    mean_cone_distance = outer_cone_distance - 0.5 * face_width

    virtual_pitch_radius = outer_cone_distance * math.tan(delta)
    virtual_tooth_count = tooth_count / cos_delta
    virtual_base_radius = virtual_pitch_radius * math.cos(alpha)
    virtual_tip_radius = virtual_pitch_radius + outer_addendum
    virtual_root_radius = virtual_pitch_radius - outer_dedendum
    tooth_half_angle = (math.pi / 2.0 + 2.0 * shift * math.tan(alpha)) * cos_delta / tooth_count
    base_half_angle = math.pi * cos_delta / tooth_count - tooth_half_angle
    tooth_thickness = 2.0 * virtual_pitch_radius * tooth_half_angle
    tip_alpha = math.acos(
        min(1.0, max(-1.0, virtual_base_radius / max(virtual_tip_radius, _EPS)))
    ) if virtual_tip_radius > virtual_base_radius else 0.0
    tip_half_angle = (
        tooth_half_angle + _involute(alpha) - _involute(tip_alpha)
        if virtual_tip_radius > virtual_base_radius else 0.0
    )
    tip_arc_thickness = 2.0 * virtual_tip_radius * tip_half_angle
    minimum_shift = ha - virtual_tooth_count * math.sin(alpha) ** 2 / 2.0
    undercut = shift < minimum_shift - 1e-9

    back_extension_requested = request.get("rim_back_extension_mm")
    if back_extension_requested is None:
        rim_back_extension = max(
            RIM_BACK_EXTENSION_MIN_MM, RIM_BACK_EXTENSION_FRACTION * face_width * sin_delta
        )
        rim_back_source = "auto"
    else:
        rim_back_extension = float(back_extension_requested)
        rim_back_source = "explicit"
    front_extension_requested = request.get("rim_front_extension_mm")
    if front_extension_requested is None:
        rim_front_extension = max(
            RIM_FRONT_EXTENSION_MIN_MM, RIM_FRONT_EXTENSION_FRACTION * face_width * sin_delta
        )
        rim_front_source = "auto"
    else:
        rim_front_extension = float(front_extension_requested)
        rim_front_source = "explicit"

    # The cone apex of the Tredgold back-cone plane and its in-plane frame.
    cone_apex_x = -outer_cone_distance / cos_delta
    cone_frame = {
        "apex": [cone_apex_x, 0.0, 0.0],
        "e1": [sin_delta, 0.0, cos_delta],
        "e2": [0.0, -1.0, 0.0],
    }
    # Outer pitch point and the two tooth corners.
    pitch_point_outer = [-outer_cone_distance * cos_delta, outer_cone_distance * sin_delta]
    pitch_point_inner = [
        pitch_point_outer[0] * inner_cone_distance / outer_cone_distance,
        pitch_point_outer[1] * inner_cone_distance / outer_cone_distance,
    ]
    tip_corner_x = cone_apex_x + virtual_tip_radius * sin_delta
    tip_corner_radius = virtual_tip_radius * cos_delta
    inner_scale = inner_cone_distance / outer_cone_distance
    inner_tip_corner_x = tip_corner_x * inner_scale
    inner_tip_corner_radius = tip_corner_radius * inner_scale
    back_face_x = tip_corner_x - rim_back_extension
    front_face_x = inner_tip_corner_x - rim_front_extension
    back_face_radius = _cone_line_radius(back_face_x, pitch_point_outer, cos_delta, sin_delta)
    front_face_radius = _cone_line_radius(front_face_x, pitch_point_inner, cos_delta, sin_delta)

    module_info = describe_module(module, rack.module_system)
    if not module_info["standard_value"]:
        warnings.append(
            warning_item(
                "gear_module_off_row",
                "Module %g mm is outside the %s rows." % (module, module_info["standard_edition"]),
                module_mm=module,
                standard_edition=module_info["standard_edition"],
            )
        )
    below_range = rack.module_min is not None and module < rack.module_min - 1e-9
    above_range = rack.module_max is not None and (
        module >= rack.module_max - 1e-9
        if rack.module_max_exclusive
        else module > rack.module_max + 1e-9
    )
    if below_range or above_range:
        warnings.append(
            warning_item(
                "gear_standard_module_range",
                "Module %g mm is outside the applicable range of %s."
                % (module, rack.standard_edition),
                module_mm=module,
                standard=rack.standard_edition,
                module_min=rack.module_min,
                module_max=rack.module_max,
                module_max_exclusive=rack.module_max_exclusive,
            )
        )
    if not rack.conformity_claim:
        warnings.append(
            warning_item(
                "gear_contour_modified",
                "Explicit coefficients make this a user-defined rack without a standard-conformity claim.",
            )
        )
    warnings.append(
        warning_item(
            "gear_bevel_nominal_projection",
            (
                "Tredgold virtual-gear projection: nominal flanks, not an exact spherical "
                "involute and not an octoid generated by a real bevel cutter."
            ),
        )
    )
    if outer_tip_diameter <= 0.0 or outer_root_diameter <= 0.0:
        errors.append(
            error_item(
                "gear_bevel_invalid_diameters",
                "The outer root and tip diameters must be positive.",
                outer_tip_diameter_mm=outer_tip_diameter,
                outer_root_diameter_mm=outer_root_diameter,
            )
        )
    if outer_root_diameter >= outer_tip_diameter - _EPS:
        errors.append(
            error_item(
                "gear_bevel_invalid_radii",
                "The outer tip diameter must exceed the outer root diameter.",
                outer_tip_diameter_mm=outer_tip_diameter,
                outer_root_diameter_mm=outer_root_diameter,
            )
        )
    if face_cone_angle >= math.radians(89.5):
        errors.append(
            error_item(
                "gear_bevel_face_cone_degenerate",
                "The face cone is almost a plane; reduce the cone angle or the addendum.",
                face_cone_angle_deg=math.degrees(face_cone_angle),
            )
        )
    width_limit = K_BE_LIMIT * outer_cone_distance
    if face_width > width_limit + 1e-9:
        warnings.append(
            warning_item(
                "gear_bevel_face_width_above_recommendation",
                "Face width exceeds the ГОСТ 19624-74 recommendation K_be <= 0.3 R_e.",
                face_width_mm=face_width,
                limit_mm=width_limit,
                ratio=face_width / outer_cone_distance,
            )
        )
    if face_width >= outer_cone_distance - _EPS:
        errors.append(
            error_item(
                "gear_bevel_face_width_exceeds_cone",
                "Face width must stay below the outer cone distance.",
                face_width_mm=face_width,
                outer_cone_distance_mm=outer_cone_distance,
            )
        )
    if virtual_tip_radius <= virtual_base_radius + 1e-9:
        errors.append(
            error_item(
                "gear_bevel_tip_below_base",
                "The virtual tip circle does not reach the virtual base circle.",
                virtual_tip_radius_mm=virtual_tip_radius,
                virtual_base_radius_mm=virtual_base_radius,
            )
        )
    if tip_arc_thickness <= 0.0:
        errors.append(
            error_item(
                "gear_bevel_tip_thickness_negative",
                "The virtual involute flanks cross before the tip circle; the tooth tip is not constructible.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    elif tip_arc_thickness < 0.25 * module:
        warnings.append(
            warning_item(
                "gear_bevel_tip_thickness_low",
                "Tooth tip thickness is below 0.25 m; the flank may be pointed and sensitive to tolerances.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    elif tip_arc_thickness < 0.3 * module:
        warnings.append(
            warning_item(
                "gear_bevel_tip_thickness_below_recommendation",
                "Tooth tip thickness is below the 0.30 m recommendation.",
                tip_thickness_mm=tip_arc_thickness,
            )
        )
    if undercut:
        warnings.append(
            warning_item(
                "gear_bevel_undercut",
                "The sharp rack cuts into the virtual involute near the base circle.",
                profile_shift=shift,
                minimum_shift=minimum_shift,
                virtual_tooth_count=virtual_tooth_count,
            )
        )
    if rim_back_extension < -1e-9 or rim_front_extension < -1e-9:
        errors.append(
            error_item(
                "gear_bevel_rim_extension_negative",
                "Rim conical end-face extensions must not be negative.",
                rim_back_extension_mm=rim_back_extension,
                rim_front_extension_mm=rim_front_extension,
            )
        )
    if front_face_x <= back_face_x + 1e-6:
        errors.append(
            error_item(
                "gear_bevel_blank_width_invalid",
                "The dish blank has no positive axial width; reduce the rim extensions.",
                back_face_x_mm=back_face_x,
                front_face_x_mm=front_face_x,
            )
        )
    if back_face_radius <= 1e-6 or front_face_radius <= 1e-6:
        errors.append(
            error_item(
                "gear_bevel_blank_face_radius_invalid",
                "A dish blank face reaches the rotation axis; reduce the rim extensions.",
                back_face_radius_mm=back_face_radius,
                front_face_radius_mm=front_face_radius,
            )
        )

    blank_profile = [
        [back_face_x, 0.0],
        [back_face_x, back_face_radius],
        [tip_corner_x, tip_corner_radius],
        [inner_tip_corner_x, inner_tip_corner_radius],
        [front_face_x, front_face_radius],
        [front_face_x, 0.0],
        [back_face_x, 0.0],
    ]
    margin = min(
        SECTION_MARGIN_MAX_MM,
        max(SECTION_MARGIN_MIN_MM, SECTION_MARGIN_FRACTION * face_width),
    )
    margin = min(margin, 0.5 * inner_cone_distance, 0.5 * outer_cone_distance)
    section_outer_cone_distance = outer_cone_distance + margin
    section_inner_cone_distance = inner_cone_distance - margin
    if section_inner_cone_distance <= 0.0:
        errors.append(
            error_item(
                "gear_bevel_inner_section_invalid",
                "The inner cut section reaches the apex with the CAD margin applied.",
                section_inner_cone_distance_mm=section_inner_cone_distance,
            )
        )
        section_inner_cone_distance = max(0.0, section_inner_cone_distance)

    geometry = BevelGearGeometry(
        request=dict(request),
        rack=rack,
        module_mm=module,
        tooth_count=tooth_count,
        pressure_angle_rad=alpha,
        profile_shift=shift,
        face_width_mm=face_width,
        face_width_source=face_width_source,
        pitch_cone_angle_rad=delta,
        face_cone_angle_rad=face_cone_angle,
        root_cone_angle_rad=root_cone_angle,
        addendum_angle_rad=addendum_angle,
        dedendum_angle_rad=dedendum_angle,
        outer_pitch_diameter_mm=outer_pitch_diameter,
        outer_cone_distance_mm=outer_cone_distance,
        inner_cone_distance_mm=inner_cone_distance,
        mean_cone_distance_mm=mean_cone_distance,
        outer_addendum_mm=outer_addendum,
        outer_dedendum_mm=outer_dedendum,
        outer_tip_diameter_mm=outer_tip_diameter,
        outer_root_diameter_mm=outer_root_diameter,
        virtual_pitch_radius_mm=virtual_pitch_radius,
        virtual_tooth_count=virtual_tooth_count,
        virtual_base_radius_mm=virtual_base_radius,
        virtual_tip_radius_mm=virtual_tip_radius,
        virtual_root_radius_mm=virtual_root_radius,
        tooth_half_angle_rad=tooth_half_angle,
        base_half_angle_rad=base_half_angle,
        tip_half_angle_rad=tip_half_angle,
        tooth_thickness_mm=tooth_thickness,
        tip_arc_thickness_mm=tip_arc_thickness,
        minimum_shift=minimum_shift,
        undercut=undercut,
        rim_back_extension_mm=rim_back_extension,
        rim_front_extension_mm=rim_front_extension,
        back_face_x_mm=back_face_x,
        back_face_radius_mm=back_face_radius,
        front_face_x_mm=front_face_x,
        front_face_radius_mm=front_face_radius,
        tip_corner_x_mm=tip_corner_x,
        tip_corner_radius_mm=tip_corner_radius,
        inner_tip_corner_x_mm=inner_tip_corner_x,
        inner_tip_corner_radius_mm=inner_tip_corner_radius,
        section_margin_mm=margin,
        section_outer_cone_distance_mm=section_outer_cone_distance,
        section_inner_cone_distance_mm=section_inner_cone_distance,
        module_info=module_info,
        cone_frame=cone_frame,
        blank_profile=blank_profile,
        warnings=warnings,
        errors=errors,
    )
    if errors:
        return geometry

    flank = build_tooth_space_flank(
        pitch_radius=virtual_pitch_radius,
        base_radius=virtual_base_radius,
        outside_radius=virtual_tip_radius,
        root_radius=virtual_root_radius,
        module_mm=module,
        pressure_angle_rad=alpha,
        base_half_angle_rad=base_half_angle,
        rack_depth_mm=(ha + clearance) * module,
        corner_depth_mm=(ha + clearance - shift) * module,
        curve_samples=curve_samples,
    )
    if flank.get("errors"):
        geometry.errors = list(flank["errors"])
        return geometry

    surface = flank["surface"]
    geometry.virtual_surface_path = surface
    geometry.virtual_surface_split_index = int(flank["surface_split_index"])
    tip_point = surface[-1]
    tip_angle = math.atan2(float(tip_point[0]), float(tip_point[1]))
    overshoot = virtual_tip_radius + max(CAP_OVERSHOOT_MM, 0.02 * virtual_tip_radius)
    cap_steps = max(8, int(12 * max(abs(tip_angle), 1e-3) / 0.1))
    cap_arc = [
        _polar(overshoot, tip_angle + (-2.0 * tip_angle) * index / cap_steps)
        for index in range(cap_steps + 1)
    ]
    mirrored_surface = [[-point[0], point[1]] for point in reversed(surface)]
    virtual_gap = _dedupe([*surface, *cap_arc, *mirrored_surface[1:], [float(surface[0][0]), float(surface[0][1])]])
    if _signed_area(virtual_gap) < 0.0:
        virtual_gap = list(reversed(virtual_gap))
    geometry.virtual_gap_outline = virtual_gap
    geometry.virtual_cap_points = [
        [float(tip_point[0]), float(tip_point[1])],
        *[[float(point[0]), float(point[1])] for point in cap_arc],
        [-float(tip_point[0]), float(tip_point[1])],
    ]

    # End view: orthographic projection of the tooth-space directions onto the
    # YZ plane, clipped by the outer tip circle of the dish.
    surface_view = [_project_to_end_view(point, cos_delta) for point in surface]
    cap_view = [_project_to_end_view(point, cos_delta) for point in cap_arc]
    right_boundary = [*surface_view, *cap_view]
    right_crossing = None
    for index in range(len(right_boundary) - 1):
        current = right_boundary[index]
        following = right_boundary[index + 1]
        current_radius = _radius(current)
        following_radius = _radius(following)
        if current_radius <= tip_corner_radius < following_radius:
            span = following_radius - current_radius
            factor = (tip_corner_radius - current_radius) / span if span > 1e-15 else 0.0
            right_crossing = (
                index,
                [
                    current[0] + (following[0] - current[0]) * factor,
                    current[1] + (following[1] - current[1]) * factor,
                ],
            )
            break
    if right_crossing is None:
        geometry.errors.append(
            error_item(
                "gear_bevel_end_view_crossing_missing",
                "The projected tooth space does not cross the outer tip circle.",
                tip_radius_mm=tip_corner_radius,
            )
        )
        return geometry
    crossing_index, crossing = right_crossing
    crossing_angle = _theta(crossing)
    pitch_angle_step = 2.0 * math.pi / tooth_count
    inner_surface = [*right_boundary[: crossing_index + 1], crossing]
    tip_arc_span = pitch_angle_step - 2.0 * crossing_angle
    tip_arc_steps = max(4, int(16 * max(abs(tip_arc_span), 1e-3) / 0.1))
    tip_arc = [
        _polar(tip_corner_radius, crossing_angle + tip_arc_span * step / tip_arc_steps)
        for step in range(tip_arc_steps + 1)
    ]
    mirrored_tooth = [
        _rotate(_mirror(point), pitch_angle_step) for point in reversed(inner_surface)
    ]
    period = _dedupe([*inner_surface, *tip_arc[1:-1], *mirrored_tooth[1:]])
    if math.dist(period[0], period[-1]) > 1e-9:
        period.append(period[0])
    geometry.end_view_period = period
    wheel: list[list[float]] = []
    for index in range(tooth_count):
        rotated = [_rotate(point, index * pitch_angle_step) for point in period]
        if wheel:
            rotated = rotated[1:]
        wheel.extend(rotated)
    wheel = _dedupe(wheel)
    if math.dist(wheel[0], wheel[-1]) > 1e-9:
        wheel.append(wheel[0])
    geometry.end_view_wheel = wheel

    # Tooth reference lines for the axial section view.
    tan_root_cone = math.tan(root_cone_angle)
    # Root cone points at the two tooth ends (where the cone faces meet the root cone).
    def _cone_intersection_x(pitch_point, cos_d, sin_d, tan_root):
        # r = p_r + (x - p_x) * cos/sin  and  r = -x * tan_root
        numerator = pitch_point[1] - pitch_point[0] * cos_d / sin_d
        denominator = -tan_root - cos_d / sin_d
        return numerator / denominator

    back_root_x = _cone_intersection_x(pitch_point_outer, cos_delta, sin_delta, tan_root_cone)
    front_root_x = _cone_intersection_x(pitch_point_inner, cos_delta, sin_delta, tan_root_cone)
    geometry.tooth_lines = {
        "back_cone": [[back_face_x, back_face_radius], [tip_corner_x, tip_corner_radius]],
        "tip_cone": [[tip_corner_x, tip_corner_radius], [inner_tip_corner_x, inner_tip_corner_radius]],
        "front_cone": [[inner_tip_corner_x, inner_tip_corner_radius], [front_face_x, front_face_radius]],
        "pitch_line": [[pitch_point_outer[0], pitch_point_outer[1]], [pitch_point_inner[0], pitch_point_inner[1]]],
        "root_line": [[back_root_x, -back_root_x * tan_root_cone], [front_root_x, -front_root_x * tan_root_cone]],
    }

    # Expected volume: dish blank minus z clipped tooth-space cones. The tooth
    # space is self-similar between the two cone planes, so its integral has a
    # closed cubic form once the clipped back-cone area is known.
    geometry.blank_volume_mm3 = _revolution_volume(blank_profile)
    gap_area = _clipped_gap_area(
        virtual_gap,
        cone_apex_x=cone_apex_x,
        sin_delta=sin_delta,
        cos_delta=cos_delta,
        tan_face_cone=math.tan(face_cone_angle),
    )
    geometry.gap_area_clipped_mm2 = gap_area
    removed_one = _removed_volume(
        virtual_gap,
        cone_apex_x=cone_apex_x,
        sin_delta=sin_delta,
        cos_delta=cos_delta,
        tan_face_cone=math.tan(face_cone_angle),
        back_face_x=back_face_x,
        front_face_x=front_face_x,
        outer_cone_distance=outer_cone_distance,
        inner_cone_distance=inner_cone_distance,
    )
    geometry.removed_volume_mm3 = tooth_count * removed_one
    geometry.expected_volume_mm3 = geometry.blank_volume_mm3 - tooth_count * removed_one
    y_values = [point[0] for point in geometry.end_view_wheel]
    z_values = [point[1] for point in geometry.end_view_wheel]
    geometry.expected_bounds_mm = [
        back_face_x, min(y_values), min(z_values),
        max(front_face_x, inner_tip_corner_x), max(y_values), max(z_values),
    ]
    geometry.diagnostics = {
        "curves": flank,
        "section_margin_mm": margin,
        "removed_volume_one_mm3": removed_one,
        "rim_back_extension_source": rim_back_source,
        "rim_front_extension_source": rim_front_source,
    }
    if geometry.expected_volume_mm3 <= 0.0 or not math.isfinite(geometry.expected_volume_mm3):
        geometry.errors.append(
            error_item(
                "gear_bevel_expected_volume_not_positive",
                "The expected bevel-gear volume is not positive.",
                expected_volume_mm3=geometry.expected_volume_mm3,
            )
        )
    return geometry


def evaluate_bevel_gear_checks(geometry: BevelGearGeometry, measurements: dict) -> dict:
    """Combine scalar diagnostics and control measurements into one report."""
    checks: list[dict] = []

    def check(code, status, message, *, value=None, limit=None, unit=None):
        checks.append(
            {
                "code": code,
                "status": status,
                "message": message,
                "value": value,
                "limit": limit,
                "unit": unit,
            }
        )

    check(
        "gear_bevel_cone_angles",
        "ok" if 5.0 <= math.degrees(geometry.pitch_cone_angle_rad) <= 85.0 else "error",
        "Pitch cone angle against the ГОСТ 19624-74 range 5..85 degrees.",
        value=math.degrees(geometry.pitch_cone_angle_rad),
        limit=[5.0, 85.0],
        unit="deg",
    )
    check(
        "gear_bevel_face_cone",
        "ok" if geometry.face_cone_angle_rad < math.radians(89.5) else "error",
        "Face cone angle stays below the degenerate flat-cone limit.",
        value=math.degrees(geometry.face_cone_angle_rad),
        limit=89.5,
        unit="deg",
    )
    diameter_order_ok = (
        0.0 < geometry.outer_root_diameter_mm < geometry.outer_pitch_diameter_mm < geometry.outer_tip_diameter_mm
    )
    check(
        "gear_bevel_radii",
        "ok" if diameter_order_ok else "error",
        "Outer root, pitch and tip diameters are ordered and positive.",
        value={
            "root_diameter_mm": geometry.outer_root_diameter_mm,
            "pitch_diameter_mm": geometry.outer_pitch_diameter_mm,
            "tip_diameter_mm": geometry.outer_tip_diameter_mm,
        },
    )
    check(
        "gear_bevel_face_width",
        "warning" if geometry.face_width_mm > K_BE_LIMIT * geometry.outer_cone_distance_mm + 1e-9 else "ok",
        "Functional face width against the ГОСТ 19624-74 recommendation K_be <= 0.3 R_e.",
        value=geometry.face_width_mm,
        limit=K_BE_LIMIT * geometry.outer_cone_distance_mm,
        unit="mm",
    )
    dish_valid = (
        geometry.front_face_x_mm > geometry.back_face_x_mm + 1e-6
        and geometry.back_face_radius_mm > 1e-6
        and geometry.front_face_radius_mm > 1e-6
    )
    check(
        "gear_bevel_dish_blank",
        "ok" if dish_valid else "error",
        "Dish blank: flat back and front faces close on the two cone-normal rim surfaces.",
        value={
            "back_face_x_mm": geometry.back_face_x_mm,
            "front_face_x_mm": geometry.front_face_x_mm,
            "back_face_radius_mm": geometry.back_face_radius_mm,
            "front_face_radius_mm": geometry.front_face_radius_mm,
            "rim_back_extension_mm": geometry.rim_back_extension_mm,
            "rim_front_extension_mm": geometry.rim_front_extension_mm,
        },
    )
    tip_value = geometry.tip_arc_thickness_mm
    if tip_value <= 0.0:
        tip_status = "error"
    elif tip_value < 0.25 * geometry.module_mm:
        tip_status = "warning"
    elif tip_value < 0.3 * geometry.module_mm:
        tip_status = "warning"
    else:
        tip_status = "ok"
    check(
        "gear_bevel_tip_thickness",
        tip_status,
        "Virtual tip circle tooth thickness against the 0.30 m recommendation.",
        value=tip_value,
        limit=0.3 * geometry.module_mm,
        unit="mm",
    )
    check(
        "gear_bevel_virtual_undercut",
        "warning" if geometry.undercut else "ok",
        "Sharp-rack undercut of the Tredgold virtual gear.",
        value=geometry.profile_shift,
        limit=geometry.minimum_shift,
        unit="coefficient",
    )
    check(
        "gear_bevel_virtual_gear",
        "ok",
        "Continuous Tredgold virtual gear parameters used for the flank.",
        value={
            "virtual_tooth_count": geometry.virtual_tooth_count,
            "virtual_pitch_diameter_mm": 2.0 * geometry.virtual_pitch_radius_mm,
            "virtual_tip_diameter_mm": 2.0 * geometry.virtual_tip_radius_mm,
            "virtual_root_diameter_mm": 2.0 * geometry.virtual_root_radius_mm,
        },
    )
    module_status = "ok" if geometry.module_info.get("standard_value") else "warning"
    check(
        "gear_module_row",
        module_status,
        "Module value against %s rows and their recorded exceptions."
        % geometry.module_info.get("standard_edition"),
        value=geometry.module_mm,
        unit="mm",
    )
    check(
        "gear_bevel_representation",
        "warning",
        (
            "Representation mode is nominal: the flank is the Tredgold projection of a "
            "sharp-rack virtual involute, not the exact spherical involute or an octoid."
        ),
    )
    failed = [item for item in checks if item["status"] == "error"]
    warnings = [item for item in checks if item["status"] == "warning"]
    return {
        "status": "error" if failed else ("warning" if warnings else "ok"),
        "checks": checks,
        "errors": failed,
        "warnings": warnings,
        "representation_mode": "nominal",
        "conformity_claim": False,
    }


def build_bevel_gear_preview(
    request: dict,
    *,
    wheel_points_per_tooth: int = 48,
) -> dict:
    """Validate the request and return the complete nominal analysis."""
    geometry = build_bevel_gear_geometry(request)
    warning_items = list(geometry.warnings)
    warnings = [str(item["message"]) for item in warning_items]
    if geometry.errors:
        return {
            "success": False,
            "family": "gear_bevel",
            "request": dict(request),
            "warnings": warnings,
            "warning_items": warning_items,
            "errors": list(geometry.errors),
            "report": {
                "status": "error",
                "checks": [],
                "errors": list(geometry.errors),
                "representation_mode": "nominal",
                "conformity_claim": False,
            },
            "geometry": {},
            "derived": {},
            "measurements": {},
        }

    module = geometry.module_mm
    constant = constant_chord(
        module_mm=module,
        profile_shift=geometry.profile_shift,
        pressure_angle_rad=geometry.pressure_angle_rad,
        pitch_radius=geometry.virtual_pitch_radius_mm,
        outside_radius=geometry.virtual_tip_radius_mm,
    )
    chordal = chordal_tooth(
        pitch_radius=geometry.virtual_pitch_radius_mm,
        tooth_thickness_mm=geometry.tooth_thickness_mm,
    )
    measurements = {
        "outer_tooth_thickness_mm": geometry.tooth_thickness_mm,
        "virtual_tooth_count": geometry.virtual_tooth_count,
        "constant_chord_mm": constant["constant_chord_mm"],
        "constant_chord_height_mm": constant["constant_chord_height_mm"],
        "chordal_tooth_thickness_mm": chordal["chordal_tooth_thickness_mm"],
        "chordal_height_mm": chordal["chordal_height_mm"],
        "tip_thickness_mm": geometry.tip_arc_thickness_mm,
        "base_pitch_mm": math.pi * module * math.cos(geometry.pressure_angle_rad),
    }
    report = evaluate_bevel_gear_checks(geometry, measurements)
    summary = {
        "tooth_type": "straight",
        "module_mm": module,
        "tooth_count": geometry.tooth_count,
        "standard": geometry.rack.standard,
        "modification": geometry.rack.modification,
        "contour_name": geometry.rack.name_ru,
        "standard_edition": geometry.rack.standard_edition,
        "pressure_angle_deg": math.degrees(geometry.pressure_angle_rad),
        "profile_shift": geometry.profile_shift,
        "face_width_mm": geometry.face_width_mm,
        "face_width_source": geometry.face_width_source,
        "pitch_cone_angle_deg": math.degrees(geometry.pitch_cone_angle_rad),
        "face_cone_angle_deg": math.degrees(geometry.face_cone_angle_rad),
        "root_cone_angle_deg": math.degrees(geometry.root_cone_angle_rad),
        "addendum_angle_deg": math.degrees(geometry.addendum_angle_rad),
        "dedendum_angle_deg": math.degrees(geometry.dedendum_angle_rad),
        "outer_pitch_diameter_mm": geometry.outer_pitch_diameter_mm,
        "outer_tip_diameter_mm": geometry.outer_tip_diameter_mm,
        "outer_root_diameter_mm": geometry.outer_root_diameter_mm,
        "outer_cone_distance_mm": geometry.outer_cone_distance_mm,
        "inner_cone_distance_mm": geometry.inner_cone_distance_mm,
        "mean_cone_distance_mm": geometry.mean_cone_distance_mm,
        "outer_addendum_mm": geometry.outer_addendum_mm,
        "outer_dedendum_mm": geometry.outer_dedendum_mm,
        "rim_back_extension_mm": geometry.rim_back_extension_mm,
        "rim_front_extension_mm": geometry.rim_front_extension_mm,
        "blank_width_mm": geometry.front_face_x_mm - geometry.back_face_x_mm,
        "back_face_diameter_mm": 2.0 * geometry.back_face_radius_mm,
        "front_face_diameter_mm": 2.0 * geometry.front_face_radius_mm,
        "section_margin_mm": geometry.section_margin_mm,
        "outer_cut_cone_distance_mm": geometry.section_outer_cone_distance_mm,
        "inner_cut_cone_distance_mm": geometry.section_inner_cone_distance_mm,
        "virtual_pitch_radius_mm": geometry.virtual_pitch_radius_mm,
        "virtual_tooth_count": geometry.virtual_tooth_count,
        "virtual_base_radius_mm": geometry.virtual_base_radius_mm,
        "virtual_tip_radius_mm": geometry.virtual_tip_radius_mm,
        "virtual_root_radius_mm": geometry.virtual_root_radius_mm,
        "tip_half_angle_deg": math.degrees(geometry.tip_half_angle_rad),
        "minimum_shift": geometry.minimum_shift,
        "undercut": geometry.undercut,
        "expected_volume_mm3": geometry.expected_volume_mm3,
        "blank_volume_mm3": geometry.blank_volume_mm3,
        "removed_volume_mm3": geometry.removed_volume_mm3,
        "representation_mode": report["representation_mode"],
        "verification_status": report["status"],
    }
    derived = {
        **summary,
        "module_row": geometry.module_info.get("row"),
        "module_status": geometry.module_info.get("status"),
        "checks": report["checks"],
    }
    return {
        "success": True,
        "family": "gear_bevel",
        "request": dict(request),
        "representation_mode": report["representation_mode"],
        "geometry": {
            "coordinate_system": "end_view_polar_yz",
            "end_view_period": geometry.end_view_period,
            "end_view_wheel": geometry.end_view_wheel,
            "virtual_surface_path": geometry.virtual_surface_path,
            "virtual_gap_outline": geometry.virtual_gap_outline,
            "cone_frame": geometry.cone_frame,
            "blank_profile": geometry.blank_profile,
            "tooth_lines": geometry.tooth_lines,
            "pitch_radius_mm": geometry.outer_pitch_diameter_mm / 2.0,
            "tip_radius_mm": geometry.tip_corner_radius_mm,
            "root_radius_mm": geometry.outer_root_diameter_mm / 2.0,
            "back_face_x_mm": geometry.back_face_x_mm,
            "front_face_x_mm": geometry.front_face_x_mm,
            "back_face_radius_mm": geometry.back_face_radius_mm,
            "front_face_radius_mm": geometry.front_face_radius_mm,
            "tip_corner_x_mm": geometry.tip_corner_x_mm,
            "tip_corner_radius_mm": geometry.tip_corner_radius_mm,
            "inner_tip_corner_x_mm": geometry.inner_tip_corner_x_mm,
            "inner_tip_corner_radius_mm": geometry.inner_tip_corner_radius_mm,
            "virtual_pitch_radius_mm": geometry.virtual_pitch_radius_mm,
            "virtual_tip_radius_mm": geometry.virtual_tip_radius_mm,
            "virtual_root_radius_mm": geometry.virtual_root_radius_mm,
            "axial_section": {
                "back_face_x_mm": geometry.back_face_x_mm,
                "front_face_x_mm": geometry.front_face_x_mm,
                "back_face_radius_mm": geometry.back_face_radius_mm,
                "front_face_radius_mm": geometry.front_face_radius_mm,
                "tip_corner_x_mm": geometry.tip_corner_x_mm,
                "tip_corner_radius_mm": geometry.tip_corner_radius_mm,
                "inner_tip_corner_x_mm": geometry.inner_tip_corner_x_mm,
                "inner_tip_corner_radius_mm": geometry.inner_tip_corner_radius_mm,
            },
        },
        "derived": derived,
        "measurements": measurements,
        "summary": summary,
        "report": report,
        "warnings": warnings,
        "warning_items": warning_items,
    }
